drop table Basketball;

create table Basketball (
	id serial primary key not null,
	rk int not null,
	player varchar not null,
	pos varchar not null,
	age int not null,
	tm varchar not null,
	"g" int not null,
	gs int not null,
	mp numeric not null,
	fg numeric not null,
	fga numeric not null,
	"fg%" numeric,
	"3p" numeric not null,
	"3pa" numeric not null,
	"3p%" numeric,
	"2p" numeric not null,
	"2pa" numeric not null,
	"2p%" numeric,
	"efg%" numeric,
	ft numeric not null,
	fta numeric not null,
	"ft%" numeric,
	orb numeric not null,
	drb numeric not null,
	trb numeric not null,
	ast numeric not null,
	stl numeric not null,
	blk numeric not null,
	tov numeric not null,
	pf numeric not null,
	pts numeric not null,
	"year" varchar not null);